# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsrtName', models.URLField(blank=True, default='')),
                ('lastName', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('municipality', models.CharField(choices=[('B', 'Bucaramanga'), ('G', 'Girón'), ('F', 'Floridablanca'), ('P', 'Piedecuesta')], max_length=1)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
